/** json-post-deserialize is MIT licensed, see /LICENSE. */
namespace HTL\JsonCheck\_Private;

const vec<State> STATE_MACHINE = vec[
  State::INVALID, //   NEUTRAL \x00
  State::INVALID, //   NEUTRAL \x01
  State::INVALID, //   NEUTRAL \x02
  State::INVALID, //   NEUTRAL \x03
  State::INVALID, //   NEUTRAL \x04
  State::INVALID, //   NEUTRAL \x05
  State::INVALID, //   NEUTRAL \x06
  State::INVALID, //   NEUTRAL \x07
  State::INVALID, //   NEUTRAL \x08
  State::NEUTRAL, //   NEUTRAL \x09
  State::NEUTRAL, //   NEUTRAL \x0a
  State::INVALID, //   NEUTRAL \x0b
  State::INVALID, //   NEUTRAL \x0c
  State::NEUTRAL, //   NEUTRAL \x0d
  State::INVALID, //   NEUTRAL \x0e
  State::INVALID, //   NEUTRAL \x0f
  State::INVALID, //   NEUTRAL \x10
  State::INVALID, //   NEUTRAL \x11
  State::INVALID, //   NEUTRAL \x12
  State::INVALID, //   NEUTRAL \x13
  State::INVALID, //   NEUTRAL \x14
  State::INVALID, //   NEUTRAL \x15
  State::INVALID, //   NEUTRAL \x16
  State::INVALID, //   NEUTRAL \x17
  State::INVALID, //   NEUTRAL \x18
  State::INVALID, //   NEUTRAL \x19
  State::INVALID, //   NEUTRAL \x1a
  State::INVALID, //   NEUTRAL \x1b
  State::INVALID, //   NEUTRAL \x1c
  State::INVALID, //   NEUTRAL \x1d
  State::INVALID, //   NEUTRAL \x1e
  State::INVALID, //   NEUTRAL \x1f
  State::NEUTRAL, //   NEUTRAL SPACE
  State::INVALID, //   NEUTRAL !
  State::IN_STRING, // NEUTRAL \
  State::INVALID, //   NEUTRAL #
  State::INVALID, //   NEUTRAL $
  State::INVALID, //   NEUTRAL %
  State::INVALID, //   NEUTRAL &
  State::INVALID, //   NEUTRAL "
  State::INVALID, //   NEUTRAL (
  State::INVALID, //   NEUTRAL )
  State::INVALID, //   NEUTRAL *
  State::INVALID, //   NEUTRAL +
  State::NEUTRAL, //   NEUTRAL ,
  State::MINUS, //     NEUTRAL -
  State::INVALID, //   NEUTRAL .
  State::INVALID, //   NEUTRAL /
  State::IN_NUMBER, // NEUTRAL 0
  State::IN_NUMBER, // NEUTRAL 1
  State::IN_NUMBER, // NEUTRAL 2
  State::IN_NUMBER, // NEUTRAL 3
  State::IN_NUMBER, // NEUTRAL 4
  State::IN_NUMBER, // NEUTRAL 5
  State::IN_NUMBER, // NEUTRAL 6
  State::IN_NUMBER, // NEUTRAL 7
  State::IN_NUMBER, // NEUTRAL 8
  State::IN_NUMBER, // NEUTRAL 9
  State::NEUTRAL, //   NEUTRAL :
  State::INVALID, //   NEUTRAL ;
  State::INVALID, //   NEUTRAL <
  State::INVALID, //   NEUTRAL =
  State::INVALID, //   NEUTRAL >
  State::INVALID, //   NEUTRAL ?
  State::INVALID, //   NEUTRAL @
  State::INVALID, //   NEUTRAL A
  State::INVALID, //   NEUTRAL B
  State::INVALID, //   NEUTRAL C
  State::INVALID, //   NEUTRAL D
  State::INVALID, //   NEUTRAL E
  State::INVALID, //   NEUTRAL F
  State::INVALID, //   NEUTRAL G
  State::INVALID, //   NEUTRAL H
  State::INVALID, //   NEUTRAL I
  State::INVALID, //   NEUTRAL J
  State::INVALID, //   NEUTRAL K
  State::INVALID, //   NEUTRAL L
  State::INVALID, //   NEUTRAL M
  State::INVALID, //   NEUTRAL N
  State::INVALID, //   NEUTRAL O
  State::INVALID, //   NEUTRAL P
  State::INVALID, //   NEUTRAL Q
  State::INVALID, //   NEUTRAL R
  State::INVALID, //   NEUTRAL S
  State::INVALID, //   NEUTRAL T
  State::INVALID, //   NEUTRAL U
  State::INVALID, //   NEUTRAL V
  State::INVALID, //   NEUTRAL W
  State::INVALID, //   NEUTRAL X
  State::INVALID, //   NEUTRAL Y
  State::INVALID, //   NEUTRAL Z
  State::NEUTRAL, //   NEUTRAL [
  State::INVALID, //   NEUTRAL \
  State::NEUTRAL, //   NEUTRAL ]
  State::INVALID, //   NEUTRAL ^
  State::INVALID, //   NEUTRAL _
  State::INVALID, //   NEUTRAL `
  State::NEUTRAL, //   NEUTRAL a
  State::INVALID, //   NEUTRAL b
  State::INVALID, //   NEUTRAL c
  State::INVALID, //   NEUTRAL d
  State::NEUTRAL, //   NEUTRAL e
  State::NEUTRAL, //   NEUTRAL f
  State::INVALID, //   NEUTRAL g
  State::INVALID, //   NEUTRAL h
  State::INVALID, //   NEUTRAL i
  State::INVALID, //   NEUTRAL j
  State::INVALID, //   NEUTRAL k
  State::NEUTRAL, //   NEUTRAL l
  State::INVALID, //   NEUTRAL m
  State::NEUTRAL, //   NEUTRAL n
  State::INVALID, //   NEUTRAL o
  State::INVALID, //   NEUTRAL p
  State::INVALID, //   NEUTRAL q
  State::NEUTRAL, //   NEUTRAL r
  State::NEUTRAL, //   NEUTRAL s
  State::NEUTRAL, //   NEUTRAL t
  State::NEUTRAL, //   NEUTRAL u
  State::INVALID, //   NEUTRAL v
  State::INVALID, //   NEUTRAL w
  State::INVALID, //   NEUTRAL x
  State::INVALID, //   NEUTRAL y
  State::INVALID, //   NEUTRAL z
  State::NEUTRAL, //   NEUTRAL {
  State::INVALID, //   NEUTRAL |
  State::NEUTRAL, //   NEUTRAL }
  State::INVALID, //   NEUTRAL ~
  State::INVALID, //   NEUTRAL \x7f
  State::INVALID, //   NEUTRAL \x80
  State::INVALID, //   NEUTRAL \x81
  State::INVALID, //   NEUTRAL \x82
  State::INVALID, //   NEUTRAL \x83
  State::INVALID, //   NEUTRAL \x84
  State::INVALID, //   NEUTRAL \x85
  State::INVALID, //   NEUTRAL \x86
  State::INVALID, //   NEUTRAL \x87
  State::INVALID, //   NEUTRAL \x88
  State::INVALID, //   NEUTRAL \x89
  State::INVALID, //   NEUTRAL \x8a
  State::INVALID, //   NEUTRAL \x8b
  State::INVALID, //   NEUTRAL \x8c
  State::INVALID, //   NEUTRAL \x8d
  State::INVALID, //   NEUTRAL \x8e
  State::INVALID, //   NEUTRAL \x8f
  State::INVALID, //   NEUTRAL \x90
  State::INVALID, //   NEUTRAL \x91
  State::INVALID, //   NEUTRAL \x92
  State::INVALID, //   NEUTRAL \x93
  State::INVALID, //   NEUTRAL \x94
  State::INVALID, //   NEUTRAL \x95
  State::INVALID, //   NEUTRAL \x96
  State::INVALID, //   NEUTRAL \x97
  State::INVALID, //   NEUTRAL \x98
  State::INVALID, //   NEUTRAL \x99
  State::INVALID, //   NEUTRAL \x9a
  State::INVALID, //   NEUTRAL \x9b
  State::INVALID, //   NEUTRAL \x9c
  State::INVALID, //   NEUTRAL \x9d
  State::INVALID, //   NEUTRAL \x9e
  State::INVALID, //   NEUTRAL \x9f
  State::INVALID, //   NEUTRAL \xa0
  State::INVALID, //   NEUTRAL \xa1
  State::INVALID, //   NEUTRAL \xa2
  State::INVALID, //   NEUTRAL \xa3
  State::INVALID, //   NEUTRAL \xa4
  State::INVALID, //   NEUTRAL \xa5
  State::INVALID, //   NEUTRAL \xa6
  State::INVALID, //   NEUTRAL \xa7
  State::INVALID, //   NEUTRAL \xa8
  State::INVALID, //   NEUTRAL \xa9
  State::INVALID, //   NEUTRAL \xaa
  State::INVALID, //   NEUTRAL \xab
  State::INVALID, //   NEUTRAL \xac
  State::INVALID, //   NEUTRAL \xad
  State::INVALID, //   NEUTRAL \xae
  State::INVALID, //   NEUTRAL \xaf
  State::INVALID, //   NEUTRAL \xb0
  State::INVALID, //   NEUTRAL \xb1
  State::INVALID, //   NEUTRAL \xb2
  State::INVALID, //   NEUTRAL \xb3
  State::INVALID, //   NEUTRAL \xb4
  State::INVALID, //   NEUTRAL \xb5
  State::INVALID, //   NEUTRAL \xb6
  State::INVALID, //   NEUTRAL \xb7
  State::INVALID, //   NEUTRAL \xb8
  State::INVALID, //   NEUTRAL \xb9
  State::INVALID, //   NEUTRAL \xba
  State::INVALID, //   NEUTRAL \xbb
  State::INVALID, //   NEUTRAL \xbc
  State::INVALID, //   NEUTRAL \xbd
  State::INVALID, //   NEUTRAL \xbe
  State::INVALID, //   NEUTRAL \xbf
  State::INVALID, //   NEUTRAL \xc0
  State::INVALID, //   NEUTRAL \xc1
  State::INVALID, //   NEUTRAL \xc2
  State::INVALID, //   NEUTRAL \xc3
  State::INVALID, //   NEUTRAL \xc4
  State::INVALID, //   NEUTRAL \xc5
  State::INVALID, //   NEUTRAL \xc6
  State::INVALID, //   NEUTRAL \xc7
  State::INVALID, //   NEUTRAL \xc8
  State::INVALID, //   NEUTRAL \xc9
  State::INVALID, //   NEUTRAL \xca
  State::INVALID, //   NEUTRAL \xcb
  State::INVALID, //   NEUTRAL \xcc
  State::INVALID, //   NEUTRAL \xcd
  State::INVALID, //   NEUTRAL \xce
  State::INVALID, //   NEUTRAL \xcf
  State::INVALID, //   NEUTRAL \xd0
  State::INVALID, //   NEUTRAL \xd1
  State::INVALID, //   NEUTRAL \xd2
  State::INVALID, //   NEUTRAL \xd3
  State::INVALID, //   NEUTRAL \xd4
  State::INVALID, //   NEUTRAL \xd5
  State::INVALID, //   NEUTRAL \xd6
  State::INVALID, //   NEUTRAL \xd7
  State::INVALID, //   NEUTRAL \xd8
  State::INVALID, //   NEUTRAL \xd9
  State::INVALID, //   NEUTRAL \xda
  State::INVALID, //   NEUTRAL \xdb
  State::INVALID, //   NEUTRAL \xdc
  State::INVALID, //   NEUTRAL \xdd
  State::INVALID, //   NEUTRAL \xde
  State::INVALID, //   NEUTRAL \xdf
  State::INVALID, //   NEUTRAL \xe0
  State::INVALID, //   NEUTRAL \xe1
  State::INVALID, //   NEUTRAL \xe2
  State::INVALID, //   NEUTRAL \xe3
  State::INVALID, //   NEUTRAL \xe4
  State::INVALID, //   NEUTRAL \xe5
  State::INVALID, //   NEUTRAL \xe6
  State::INVALID, //   NEUTRAL \xe7
  State::INVALID, //   NEUTRAL \xe8
  State::INVALID, //   NEUTRAL \xe9
  State::INVALID, //   NEUTRAL \xea
  State::INVALID, //   NEUTRAL \xeb
  State::INVALID, //   NEUTRAL \xec
  State::INVALID, //   NEUTRAL \xed
  State::INVALID, //   NEUTRAL \xee
  State::INVALID, //   NEUTRAL \xef
  State::INVALID, //   NEUTRAL \xf0
  State::INVALID, //   NEUTRAL \xf1
  State::INVALID, //   NEUTRAL \xf2
  State::INVALID, //   NEUTRAL \xf3
  State::INVALID, //   NEUTRAL \xf4
  State::INVALID, //   NEUTRAL \xf5
  State::INVALID, //   NEUTRAL \xf6
  State::INVALID, //   NEUTRAL \xf7
  State::INVALID, //   NEUTRAL \xf8
  State::INVALID, //   NEUTRAL \xf9
  State::INVALID, //   NEUTRAL \xfa
  State::INVALID, //   NEUTRAL \xfb
  State::INVALID, //   NEUTRAL \xfc
  State::INVALID, //   NEUTRAL \xfd
  State::INVALID, //   NEUTRAL \xfe
  State::INVALID, //   NEUTRAL \xff
  State::IN_STRING, // IN_STRING \x00
  State::IN_STRING, // IN_STRING \x01
  State::IN_STRING, // IN_STRING \x02
  State::IN_STRING, // IN_STRING \x03
  State::IN_STRING, // IN_STRING \x04
  State::IN_STRING, // IN_STRING \x05
  State::IN_STRING, // IN_STRING \x06
  State::IN_STRING, // IN_STRING \x07
  State::IN_STRING, // IN_STRING \x08
  State::IN_STRING, // IN_STRING \x09
  State::IN_STRING, // IN_STRING \x0a
  State::IN_STRING, // IN_STRING \x0b
  State::IN_STRING, // IN_STRING \x0c
  State::IN_STRING, // IN_STRING \x0d
  State::IN_STRING, // IN_STRING \x0e
  State::IN_STRING, // IN_STRING \x0f
  State::IN_STRING, // IN_STRING \x10
  State::IN_STRING, // IN_STRING \x11
  State::IN_STRING, // IN_STRING \x12
  State::IN_STRING, // IN_STRING \x13
  State::IN_STRING, // IN_STRING \x14
  State::IN_STRING, // IN_STRING \x15
  State::IN_STRING, // IN_STRING \x16
  State::IN_STRING, // IN_STRING \x17
  State::IN_STRING, // IN_STRING \x18
  State::IN_STRING, // IN_STRING \x19
  State::IN_STRING, // IN_STRING \x1a
  State::IN_STRING, // IN_STRING \x1b
  State::IN_STRING, // IN_STRING \x1c
  State::IN_STRING, // IN_STRING \x1d
  State::IN_STRING, // IN_STRING \x1e
  State::IN_STRING, // IN_STRING \x1f
  State::IN_STRING, // IN_STRING SPACE
  State::IN_STRING, // IN_STRING !
  State::NEUTRAL, //   IN_STRING \
  State::IN_STRING, // IN_STRING #
  State::IN_STRING, // IN_STRING $
  State::IN_STRING, // IN_STRING %
  State::IN_STRING, // IN_STRING &
  State::IN_STRING, // IN_STRING "
  State::IN_STRING, // IN_STRING (
  State::IN_STRING, // IN_STRING )
  State::IN_STRING, // IN_STRING *
  State::IN_STRING, // IN_STRING +
  State::IN_STRING, // IN_STRING ,
  State::IN_STRING, // IN_STRING -
  State::IN_STRING, // IN_STRING .
  State::IN_STRING, // IN_STRING /
  State::IN_STRING, // IN_STRING 0
  State::IN_STRING, // IN_STRING 1
  State::IN_STRING, // IN_STRING 2
  State::IN_STRING, // IN_STRING 3
  State::IN_STRING, // IN_STRING 4
  State::IN_STRING, // IN_STRING 5
  State::IN_STRING, // IN_STRING 6
  State::IN_STRING, // IN_STRING 7
  State::IN_STRING, // IN_STRING 8
  State::IN_STRING, // IN_STRING 9
  State::IN_STRING, // IN_STRING :
  State::IN_STRING, // IN_STRING ;
  State::IN_STRING, // IN_STRING <
  State::IN_STRING, // IN_STRING =
  State::IN_STRING, // IN_STRING >
  State::IN_STRING, // IN_STRING ?
  State::IN_STRING, // IN_STRING @
  State::IN_STRING, // IN_STRING A
  State::IN_STRING, // IN_STRING B
  State::IN_STRING, // IN_STRING C
  State::IN_STRING, // IN_STRING D
  State::IN_STRING, // IN_STRING E
  State::IN_STRING, // IN_STRING F
  State::IN_STRING, // IN_STRING G
  State::IN_STRING, // IN_STRING H
  State::IN_STRING, // IN_STRING I
  State::IN_STRING, // IN_STRING J
  State::IN_STRING, // IN_STRING K
  State::IN_STRING, // IN_STRING L
  State::IN_STRING, // IN_STRING M
  State::IN_STRING, // IN_STRING N
  State::IN_STRING, // IN_STRING O
  State::IN_STRING, // IN_STRING P
  State::IN_STRING, // IN_STRING Q
  State::IN_STRING, // IN_STRING R
  State::IN_STRING, // IN_STRING S
  State::IN_STRING, // IN_STRING T
  State::IN_STRING, // IN_STRING U
  State::IN_STRING, // IN_STRING V
  State::IN_STRING, // IN_STRING W
  State::IN_STRING, // IN_STRING X
  State::IN_STRING, // IN_STRING Y
  State::IN_STRING, // IN_STRING Z
  State::IN_STRING, // IN_STRING [
  State::ESCAPE, //    IN_STRING \
  State::IN_STRING, // IN_STRING ]
  State::IN_STRING, // IN_STRING ^
  State::IN_STRING, // IN_STRING _
  State::IN_STRING, // IN_STRING `
  State::IN_STRING, // IN_STRING a
  State::IN_STRING, // IN_STRING b
  State::IN_STRING, // IN_STRING c
  State::IN_STRING, // IN_STRING d
  State::IN_STRING, // IN_STRING e
  State::IN_STRING, // IN_STRING f
  State::IN_STRING, // IN_STRING g
  State::IN_STRING, // IN_STRING h
  State::IN_STRING, // IN_STRING i
  State::IN_STRING, // IN_STRING j
  State::IN_STRING, // IN_STRING k
  State::IN_STRING, // IN_STRING l
  State::IN_STRING, // IN_STRING m
  State::IN_STRING, // IN_STRING n
  State::IN_STRING, // IN_STRING o
  State::IN_STRING, // IN_STRING p
  State::IN_STRING, // IN_STRING q
  State::IN_STRING, // IN_STRING r
  State::IN_STRING, // IN_STRING s
  State::IN_STRING, // IN_STRING t
  State::IN_STRING, // IN_STRING u
  State::IN_STRING, // IN_STRING v
  State::IN_STRING, // IN_STRING w
  State::IN_STRING, // IN_STRING x
  State::IN_STRING, // IN_STRING y
  State::IN_STRING, // IN_STRING z
  State::IN_STRING, // IN_STRING {
  State::IN_STRING, // IN_STRING |
  State::IN_STRING, // IN_STRING }
  State::IN_STRING, // IN_STRING ~
  State::IN_STRING, // IN_STRING \x7f
  State::IN_STRING, // IN_STRING \x80
  State::IN_STRING, // IN_STRING \x81
  State::IN_STRING, // IN_STRING \x82
  State::IN_STRING, // IN_STRING \x83
  State::IN_STRING, // IN_STRING \x84
  State::IN_STRING, // IN_STRING \x85
  State::IN_STRING, // IN_STRING \x86
  State::IN_STRING, // IN_STRING \x87
  State::IN_STRING, // IN_STRING \x88
  State::IN_STRING, // IN_STRING \x89
  State::IN_STRING, // IN_STRING \x8a
  State::IN_STRING, // IN_STRING \x8b
  State::IN_STRING, // IN_STRING \x8c
  State::IN_STRING, // IN_STRING \x8d
  State::IN_STRING, // IN_STRING \x8e
  State::IN_STRING, // IN_STRING \x8f
  State::IN_STRING, // IN_STRING \x90
  State::IN_STRING, // IN_STRING \x91
  State::IN_STRING, // IN_STRING \x92
  State::IN_STRING, // IN_STRING \x93
  State::IN_STRING, // IN_STRING \x94
  State::IN_STRING, // IN_STRING \x95
  State::IN_STRING, // IN_STRING \x96
  State::IN_STRING, // IN_STRING \x97
  State::IN_STRING, // IN_STRING \x98
  State::IN_STRING, // IN_STRING \x99
  State::IN_STRING, // IN_STRING \x9a
  State::IN_STRING, // IN_STRING \x9b
  State::IN_STRING, // IN_STRING \x9c
  State::IN_STRING, // IN_STRING \x9d
  State::IN_STRING, // IN_STRING \x9e
  State::IN_STRING, // IN_STRING \x9f
  State::IN_STRING, // IN_STRING \xa0
  State::IN_STRING, // IN_STRING \xa1
  State::IN_STRING, // IN_STRING \xa2
  State::IN_STRING, // IN_STRING \xa3
  State::IN_STRING, // IN_STRING \xa4
  State::IN_STRING, // IN_STRING \xa5
  State::IN_STRING, // IN_STRING \xa6
  State::IN_STRING, // IN_STRING \xa7
  State::IN_STRING, // IN_STRING \xa8
  State::IN_STRING, // IN_STRING \xa9
  State::IN_STRING, // IN_STRING \xaa
  State::IN_STRING, // IN_STRING \xab
  State::IN_STRING, // IN_STRING \xac
  State::IN_STRING, // IN_STRING \xad
  State::IN_STRING, // IN_STRING \xae
  State::IN_STRING, // IN_STRING \xaf
  State::IN_STRING, // IN_STRING \xb0
  State::IN_STRING, // IN_STRING \xb1
  State::IN_STRING, // IN_STRING \xb2
  State::IN_STRING, // IN_STRING \xb3
  State::IN_STRING, // IN_STRING \xb4
  State::IN_STRING, // IN_STRING \xb5
  State::IN_STRING, // IN_STRING \xb6
  State::IN_STRING, // IN_STRING \xb7
  State::IN_STRING, // IN_STRING \xb8
  State::IN_STRING, // IN_STRING \xb9
  State::IN_STRING, // IN_STRING \xba
  State::IN_STRING, // IN_STRING \xbb
  State::IN_STRING, // IN_STRING \xbc
  State::IN_STRING, // IN_STRING \xbd
  State::IN_STRING, // IN_STRING \xbe
  State::IN_STRING, // IN_STRING \xbf
  State::IN_STRING, // IN_STRING \xc0
  State::IN_STRING, // IN_STRING \xc1
  State::IN_STRING, // IN_STRING \xc2
  State::IN_STRING, // IN_STRING \xc3
  State::IN_STRING, // IN_STRING \xc4
  State::IN_STRING, // IN_STRING \xc5
  State::IN_STRING, // IN_STRING \xc6
  State::IN_STRING, // IN_STRING \xc7
  State::IN_STRING, // IN_STRING \xc8
  State::IN_STRING, // IN_STRING \xc9
  State::IN_STRING, // IN_STRING \xca
  State::IN_STRING, // IN_STRING \xcb
  State::IN_STRING, // IN_STRING \xcc
  State::IN_STRING, // IN_STRING \xcd
  State::IN_STRING, // IN_STRING \xce
  State::IN_STRING, // IN_STRING \xcf
  State::IN_STRING, // IN_STRING \xd0
  State::IN_STRING, // IN_STRING \xd1
  State::IN_STRING, // IN_STRING \xd2
  State::IN_STRING, // IN_STRING \xd3
  State::IN_STRING, // IN_STRING \xd4
  State::IN_STRING, // IN_STRING \xd5
  State::IN_STRING, // IN_STRING \xd6
  State::IN_STRING, // IN_STRING \xd7
  State::IN_STRING, // IN_STRING \xd8
  State::IN_STRING, // IN_STRING \xd9
  State::IN_STRING, // IN_STRING \xda
  State::IN_STRING, // IN_STRING \xdb
  State::IN_STRING, // IN_STRING \xdc
  State::IN_STRING, // IN_STRING \xdd
  State::IN_STRING, // IN_STRING \xde
  State::IN_STRING, // IN_STRING \xdf
  State::IN_STRING, // IN_STRING \xe0
  State::IN_STRING, // IN_STRING \xe1
  State::IN_STRING, // IN_STRING \xe2
  State::IN_STRING, // IN_STRING \xe3
  State::IN_STRING, // IN_STRING \xe4
  State::IN_STRING, // IN_STRING \xe5
  State::IN_STRING, // IN_STRING \xe6
  State::IN_STRING, // IN_STRING \xe7
  State::IN_STRING, // IN_STRING \xe8
  State::IN_STRING, // IN_STRING \xe9
  State::IN_STRING, // IN_STRING \xea
  State::IN_STRING, // IN_STRING \xeb
  State::IN_STRING, // IN_STRING \xec
  State::IN_STRING, // IN_STRING \xed
  State::IN_STRING, // IN_STRING \xee
  State::IN_STRING, // IN_STRING \xef
  State::IN_STRING, // IN_STRING \xf0
  State::IN_STRING, // IN_STRING \xf1
  State::IN_STRING, // IN_STRING \xf2
  State::IN_STRING, // IN_STRING \xf3
  State::IN_STRING, // IN_STRING \xf4
  State::IN_STRING, // IN_STRING \xf5
  State::IN_STRING, // IN_STRING \xf6
  State::IN_STRING, // IN_STRING \xf7
  State::IN_STRING, // IN_STRING \xf8
  State::IN_STRING, // IN_STRING \xf9
  State::IN_STRING, // IN_STRING \xfa
  State::IN_STRING, // IN_STRING \xfb
  State::IN_STRING, // IN_STRING \xfc
  State::IN_STRING, // IN_STRING \xfd
  State::IN_STRING, // IN_STRING \xfe
  State::IN_STRING, // IN_STRING \xff
  State::IN_STRING, // ESCAPE \x00
  State::IN_STRING, // ESCAPE \x01
  State::IN_STRING, // ESCAPE \x02
  State::IN_STRING, // ESCAPE \x03
  State::IN_STRING, // ESCAPE \x04
  State::IN_STRING, // ESCAPE \x05
  State::IN_STRING, // ESCAPE \x06
  State::IN_STRING, // ESCAPE \x07
  State::IN_STRING, // ESCAPE \x08
  State::IN_STRING, // ESCAPE \x09
  State::IN_STRING, // ESCAPE \x0a
  State::IN_STRING, // ESCAPE \x0b
  State::IN_STRING, // ESCAPE \x0c
  State::IN_STRING, // ESCAPE \x0d
  State::IN_STRING, // ESCAPE \x0e
  State::IN_STRING, // ESCAPE \x0f
  State::IN_STRING, // ESCAPE \x10
  State::IN_STRING, // ESCAPE \x11
  State::IN_STRING, // ESCAPE \x12
  State::IN_STRING, // ESCAPE \x13
  State::IN_STRING, // ESCAPE \x14
  State::IN_STRING, // ESCAPE \x15
  State::IN_STRING, // ESCAPE \x16
  State::IN_STRING, // ESCAPE \x17
  State::IN_STRING, // ESCAPE \x18
  State::IN_STRING, // ESCAPE \x19
  State::IN_STRING, // ESCAPE \x1a
  State::IN_STRING, // ESCAPE \x1b
  State::IN_STRING, // ESCAPE \x1c
  State::IN_STRING, // ESCAPE \x1d
  State::IN_STRING, // ESCAPE \x1e
  State::IN_STRING, // ESCAPE \x1f
  State::IN_STRING, // ESCAPE SPACE
  State::IN_STRING, // ESCAPE !
  State::IN_STRING, // ESCAPE \
  State::IN_STRING, // ESCAPE #
  State::IN_STRING, // ESCAPE $
  State::IN_STRING, // ESCAPE %
  State::IN_STRING, // ESCAPE &
  State::IN_STRING, // ESCAPE "
  State::IN_STRING, // ESCAPE (
  State::IN_STRING, // ESCAPE )
  State::IN_STRING, // ESCAPE *
  State::IN_STRING, // ESCAPE +
  State::IN_STRING, // ESCAPE ,
  State::IN_STRING, // ESCAPE -
  State::IN_STRING, // ESCAPE .
  State::IN_STRING, // ESCAPE /
  State::IN_STRING, // ESCAPE 0
  State::IN_STRING, // ESCAPE 1
  State::IN_STRING, // ESCAPE 2
  State::IN_STRING, // ESCAPE 3
  State::IN_STRING, // ESCAPE 4
  State::IN_STRING, // ESCAPE 5
  State::IN_STRING, // ESCAPE 6
  State::IN_STRING, // ESCAPE 7
  State::IN_STRING, // ESCAPE 8
  State::IN_STRING, // ESCAPE 9
  State::IN_STRING, // ESCAPE :
  State::IN_STRING, // ESCAPE ;
  State::IN_STRING, // ESCAPE <
  State::IN_STRING, // ESCAPE =
  State::IN_STRING, // ESCAPE >
  State::IN_STRING, // ESCAPE ?
  State::IN_STRING, // ESCAPE @
  State::IN_STRING, // ESCAPE A
  State::IN_STRING, // ESCAPE B
  State::IN_STRING, // ESCAPE C
  State::IN_STRING, // ESCAPE D
  State::IN_STRING, // ESCAPE E
  State::IN_STRING, // ESCAPE F
  State::IN_STRING, // ESCAPE G
  State::IN_STRING, // ESCAPE H
  State::IN_STRING, // ESCAPE I
  State::IN_STRING, // ESCAPE J
  State::IN_STRING, // ESCAPE K
  State::IN_STRING, // ESCAPE L
  State::IN_STRING, // ESCAPE M
  State::IN_STRING, // ESCAPE N
  State::IN_STRING, // ESCAPE O
  State::IN_STRING, // ESCAPE P
  State::IN_STRING, // ESCAPE Q
  State::IN_STRING, // ESCAPE R
  State::IN_STRING, // ESCAPE S
  State::IN_STRING, // ESCAPE T
  State::IN_STRING, // ESCAPE U
  State::IN_STRING, // ESCAPE V
  State::IN_STRING, // ESCAPE W
  State::IN_STRING, // ESCAPE X
  State::IN_STRING, // ESCAPE Y
  State::IN_STRING, // ESCAPE Z
  State::IN_STRING, // ESCAPE [
  State::IN_STRING, // ESCAPE \
  State::IN_STRING, // ESCAPE ]
  State::IN_STRING, // ESCAPE ^
  State::IN_STRING, // ESCAPE _
  State::IN_STRING, // ESCAPE `
  State::IN_STRING, // ESCAPE a
  State::IN_STRING, // ESCAPE b
  State::IN_STRING, // ESCAPE c
  State::IN_STRING, // ESCAPE d
  State::IN_STRING, // ESCAPE e
  State::IN_STRING, // ESCAPE f
  State::IN_STRING, // ESCAPE g
  State::IN_STRING, // ESCAPE h
  State::IN_STRING, // ESCAPE i
  State::IN_STRING, // ESCAPE j
  State::IN_STRING, // ESCAPE k
  State::IN_STRING, // ESCAPE l
  State::IN_STRING, // ESCAPE m
  State::IN_STRING, // ESCAPE n
  State::IN_STRING, // ESCAPE o
  State::IN_STRING, // ESCAPE p
  State::IN_STRING, // ESCAPE q
  State::IN_STRING, // ESCAPE r
  State::IN_STRING, // ESCAPE s
  State::IN_STRING, // ESCAPE t
  State::IN_STRING, // ESCAPE u
  State::IN_STRING, // ESCAPE v
  State::IN_STRING, // ESCAPE w
  State::IN_STRING, // ESCAPE x
  State::IN_STRING, // ESCAPE y
  State::IN_STRING, // ESCAPE z
  State::IN_STRING, // ESCAPE {
  State::IN_STRING, // ESCAPE |
  State::IN_STRING, // ESCAPE }
  State::IN_STRING, // ESCAPE ~
  State::IN_STRING, // ESCAPE \x7f
  State::IN_STRING, // ESCAPE \x80
  State::IN_STRING, // ESCAPE \x81
  State::IN_STRING, // ESCAPE \x82
  State::IN_STRING, // ESCAPE \x83
  State::IN_STRING, // ESCAPE \x84
  State::IN_STRING, // ESCAPE \x85
  State::IN_STRING, // ESCAPE \x86
  State::IN_STRING, // ESCAPE \x87
  State::IN_STRING, // ESCAPE \x88
  State::IN_STRING, // ESCAPE \x89
  State::IN_STRING, // ESCAPE \x8a
  State::IN_STRING, // ESCAPE \x8b
  State::IN_STRING, // ESCAPE \x8c
  State::IN_STRING, // ESCAPE \x8d
  State::IN_STRING, // ESCAPE \x8e
  State::IN_STRING, // ESCAPE \x8f
  State::IN_STRING, // ESCAPE \x90
  State::IN_STRING, // ESCAPE \x91
  State::IN_STRING, // ESCAPE \x92
  State::IN_STRING, // ESCAPE \x93
  State::IN_STRING, // ESCAPE \x94
  State::IN_STRING, // ESCAPE \x95
  State::IN_STRING, // ESCAPE \x96
  State::IN_STRING, // ESCAPE \x97
  State::IN_STRING, // ESCAPE \x98
  State::IN_STRING, // ESCAPE \x99
  State::IN_STRING, // ESCAPE \x9a
  State::IN_STRING, // ESCAPE \x9b
  State::IN_STRING, // ESCAPE \x9c
  State::IN_STRING, // ESCAPE \x9d
  State::IN_STRING, // ESCAPE \x9e
  State::IN_STRING, // ESCAPE \x9f
  State::IN_STRING, // ESCAPE \xa0
  State::IN_STRING, // ESCAPE \xa1
  State::IN_STRING, // ESCAPE \xa2
  State::IN_STRING, // ESCAPE \xa3
  State::IN_STRING, // ESCAPE \xa4
  State::IN_STRING, // ESCAPE \xa5
  State::IN_STRING, // ESCAPE \xa6
  State::IN_STRING, // ESCAPE \xa7
  State::IN_STRING, // ESCAPE \xa8
  State::IN_STRING, // ESCAPE \xa9
  State::IN_STRING, // ESCAPE \xaa
  State::IN_STRING, // ESCAPE \xab
  State::IN_STRING, // ESCAPE \xac
  State::IN_STRING, // ESCAPE \xad
  State::IN_STRING, // ESCAPE \xae
  State::IN_STRING, // ESCAPE \xaf
  State::IN_STRING, // ESCAPE \xb0
  State::IN_STRING, // ESCAPE \xb1
  State::IN_STRING, // ESCAPE \xb2
  State::IN_STRING, // ESCAPE \xb3
  State::IN_STRING, // ESCAPE \xb4
  State::IN_STRING, // ESCAPE \xb5
  State::IN_STRING, // ESCAPE \xb6
  State::IN_STRING, // ESCAPE \xb7
  State::IN_STRING, // ESCAPE \xb8
  State::IN_STRING, // ESCAPE \xb9
  State::IN_STRING, // ESCAPE \xba
  State::IN_STRING, // ESCAPE \xbb
  State::IN_STRING, // ESCAPE \xbc
  State::IN_STRING, // ESCAPE \xbd
  State::IN_STRING, // ESCAPE \xbe
  State::IN_STRING, // ESCAPE \xbf
  State::IN_STRING, // ESCAPE \xc0
  State::IN_STRING, // ESCAPE \xc1
  State::IN_STRING, // ESCAPE \xc2
  State::IN_STRING, // ESCAPE \xc3
  State::IN_STRING, // ESCAPE \xc4
  State::IN_STRING, // ESCAPE \xc5
  State::IN_STRING, // ESCAPE \xc6
  State::IN_STRING, // ESCAPE \xc7
  State::IN_STRING, // ESCAPE \xc8
  State::IN_STRING, // ESCAPE \xc9
  State::IN_STRING, // ESCAPE \xca
  State::IN_STRING, // ESCAPE \xcb
  State::IN_STRING, // ESCAPE \xcc
  State::IN_STRING, // ESCAPE \xcd
  State::IN_STRING, // ESCAPE \xce
  State::IN_STRING, // ESCAPE \xcf
  State::IN_STRING, // ESCAPE \xd0
  State::IN_STRING, // ESCAPE \xd1
  State::IN_STRING, // ESCAPE \xd2
  State::IN_STRING, // ESCAPE \xd3
  State::IN_STRING, // ESCAPE \xd4
  State::IN_STRING, // ESCAPE \xd5
  State::IN_STRING, // ESCAPE \xd6
  State::IN_STRING, // ESCAPE \xd7
  State::IN_STRING, // ESCAPE \xd8
  State::IN_STRING, // ESCAPE \xd9
  State::IN_STRING, // ESCAPE \xda
  State::IN_STRING, // ESCAPE \xdb
  State::IN_STRING, // ESCAPE \xdc
  State::IN_STRING, // ESCAPE \xdd
  State::IN_STRING, // ESCAPE \xde
  State::IN_STRING, // ESCAPE \xdf
  State::IN_STRING, // ESCAPE \xe0
  State::IN_STRING, // ESCAPE \xe1
  State::IN_STRING, // ESCAPE \xe2
  State::IN_STRING, // ESCAPE \xe3
  State::IN_STRING, // ESCAPE \xe4
  State::IN_STRING, // ESCAPE \xe5
  State::IN_STRING, // ESCAPE \xe6
  State::IN_STRING, // ESCAPE \xe7
  State::IN_STRING, // ESCAPE \xe8
  State::IN_STRING, // ESCAPE \xe9
  State::IN_STRING, // ESCAPE \xea
  State::IN_STRING, // ESCAPE \xeb
  State::IN_STRING, // ESCAPE \xec
  State::IN_STRING, // ESCAPE \xed
  State::IN_STRING, // ESCAPE \xee
  State::IN_STRING, // ESCAPE \xef
  State::IN_STRING, // ESCAPE \xf0
  State::IN_STRING, // ESCAPE \xf1
  State::IN_STRING, // ESCAPE \xf2
  State::IN_STRING, // ESCAPE \xf3
  State::IN_STRING, // ESCAPE \xf4
  State::IN_STRING, // ESCAPE \xf5
  State::IN_STRING, // ESCAPE \xf6
  State::IN_STRING, // ESCAPE \xf7
  State::IN_STRING, // ESCAPE \xf8
  State::IN_STRING, // ESCAPE \xf9
  State::IN_STRING, // ESCAPE \xfa
  State::IN_STRING, // ESCAPE \xfb
  State::IN_STRING, // ESCAPE \xfc
  State::IN_STRING, // ESCAPE \xfd
  State::IN_STRING, // ESCAPE \xfe
  State::IN_STRING, // ESCAPE \xff
  State::INVALID, //   MINUS \x00
  State::INVALID, //   MINUS \x01
  State::INVALID, //   MINUS \x02
  State::INVALID, //   MINUS \x03
  State::INVALID, //   MINUS \x04
  State::INVALID, //   MINUS \x05
  State::INVALID, //   MINUS \x06
  State::INVALID, //   MINUS \x07
  State::INVALID, //   MINUS \x08
  State::INVALID, //   MINUS \x09
  State::INVALID, //   MINUS \x0a
  State::INVALID, //   MINUS \x0b
  State::INVALID, //   MINUS \x0c
  State::INVALID, //   MINUS \x0d
  State::INVALID, //   MINUS \x0e
  State::INVALID, //   MINUS \x0f
  State::INVALID, //   MINUS \x10
  State::INVALID, //   MINUS \x11
  State::INVALID, //   MINUS \x12
  State::INVALID, //   MINUS \x13
  State::INVALID, //   MINUS \x14
  State::INVALID, //   MINUS \x15
  State::INVALID, //   MINUS \x16
  State::INVALID, //   MINUS \x17
  State::INVALID, //   MINUS \x18
  State::INVALID, //   MINUS \x19
  State::INVALID, //   MINUS \x1a
  State::INVALID, //   MINUS \x1b
  State::INVALID, //   MINUS \x1c
  State::INVALID, //   MINUS \x1d
  State::INVALID, //   MINUS \x1e
  State::INVALID, //   MINUS \x1f
  State::INVALID, //   MINUS SPACE
  State::INVALID, //   MINUS !
  State::INVALID, //   MINUS \
  State::INVALID, //   MINUS #
  State::INVALID, //   MINUS $
  State::INVALID, //   MINUS %
  State::INVALID, //   MINUS &
  State::INVALID, //   MINUS "
  State::INVALID, //   MINUS (
  State::INVALID, //   MINUS )
  State::INVALID, //   MINUS *
  State::INVALID, //   MINUS +
  State::INVALID, //   MINUS ,
  State::INVALID, //   MINUS -
  State::INVALID, //   MINUS .
  State::INVALID, //   MINUS /
  State::IN_NUMBER, // MINUS 0
  State::IN_NUMBER, // MINUS 1
  State::IN_NUMBER, // MINUS 2
  State::IN_NUMBER, // MINUS 3
  State::IN_NUMBER, // MINUS 4
  State::IN_NUMBER, // MINUS 5
  State::IN_NUMBER, // MINUS 6
  State::IN_NUMBER, // MINUS 7
  State::IN_NUMBER, // MINUS 8
  State::IN_NUMBER, // MINUS 9
  State::INVALID, //   MINUS :
  State::INVALID, //   MINUS ;
  State::INVALID, //   MINUS <
  State::INVALID, //   MINUS =
  State::INVALID, //   MINUS >
  State::INVALID, //   MINUS ?
  State::INVALID, //   MINUS @
  State::INVALID, //   MINUS A
  State::INVALID, //   MINUS B
  State::INVALID, //   MINUS C
  State::INVALID, //   MINUS D
  State::INVALID, //   MINUS E
  State::INVALID, //   MINUS F
  State::INVALID, //   MINUS G
  State::INVALID, //   MINUS H
  State::INVALID, //   MINUS I
  State::INVALID, //   MINUS J
  State::INVALID, //   MINUS K
  State::INVALID, //   MINUS L
  State::INVALID, //   MINUS M
  State::INVALID, //   MINUS N
  State::INVALID, //   MINUS O
  State::INVALID, //   MINUS P
  State::INVALID, //   MINUS Q
  State::INVALID, //   MINUS R
  State::INVALID, //   MINUS S
  State::INVALID, //   MINUS T
  State::INVALID, //   MINUS U
  State::INVALID, //   MINUS V
  State::INVALID, //   MINUS W
  State::INVALID, //   MINUS X
  State::INVALID, //   MINUS Y
  State::INVALID, //   MINUS Z
  State::INVALID, //   MINUS [
  State::INVALID, //   MINUS \
  State::INVALID, //   MINUS ]
  State::INVALID, //   MINUS ^
  State::INVALID, //   MINUS _
  State::INVALID, //   MINUS `
  State::INVALID, //   MINUS a
  State::INVALID, //   MINUS b
  State::INVALID, //   MINUS c
  State::INVALID, //   MINUS d
  State::INVALID, //   MINUS e
  State::INVALID, //   MINUS f
  State::INVALID, //   MINUS g
  State::INVALID, //   MINUS h
  State::INVALID, //   MINUS i
  State::INVALID, //   MINUS j
  State::INVALID, //   MINUS k
  State::INVALID, //   MINUS l
  State::INVALID, //   MINUS m
  State::INVALID, //   MINUS n
  State::INVALID, //   MINUS o
  State::INVALID, //   MINUS p
  State::INVALID, //   MINUS q
  State::INVALID, //   MINUS r
  State::INVALID, //   MINUS s
  State::INVALID, //   MINUS t
  State::INVALID, //   MINUS u
  State::INVALID, //   MINUS v
  State::INVALID, //   MINUS w
  State::INVALID, //   MINUS x
  State::INVALID, //   MINUS y
  State::INVALID, //   MINUS z
  State::INVALID, //   MINUS {
  State::INVALID, //   MINUS |
  State::INVALID, //   MINUS }
  State::INVALID, //   MINUS ~
  State::INVALID, //   MINUS \x7f
  State::INVALID, //   MINUS \x80
  State::INVALID, //   MINUS \x81
  State::INVALID, //   MINUS \x82
  State::INVALID, //   MINUS \x83
  State::INVALID, //   MINUS \x84
  State::INVALID, //   MINUS \x85
  State::INVALID, //   MINUS \x86
  State::INVALID, //   MINUS \x87
  State::INVALID, //   MINUS \x88
  State::INVALID, //   MINUS \x89
  State::INVALID, //   MINUS \x8a
  State::INVALID, //   MINUS \x8b
  State::INVALID, //   MINUS \x8c
  State::INVALID, //   MINUS \x8d
  State::INVALID, //   MINUS \x8e
  State::INVALID, //   MINUS \x8f
  State::INVALID, //   MINUS \x90
  State::INVALID, //   MINUS \x91
  State::INVALID, //   MINUS \x92
  State::INVALID, //   MINUS \x93
  State::INVALID, //   MINUS \x94
  State::INVALID, //   MINUS \x95
  State::INVALID, //   MINUS \x96
  State::INVALID, //   MINUS \x97
  State::INVALID, //   MINUS \x98
  State::INVALID, //   MINUS \x99
  State::INVALID, //   MINUS \x9a
  State::INVALID, //   MINUS \x9b
  State::INVALID, //   MINUS \x9c
  State::INVALID, //   MINUS \x9d
  State::INVALID, //   MINUS \x9e
  State::INVALID, //   MINUS \x9f
  State::INVALID, //   MINUS \xa0
  State::INVALID, //   MINUS \xa1
  State::INVALID, //   MINUS \xa2
  State::INVALID, //   MINUS \xa3
  State::INVALID, //   MINUS \xa4
  State::INVALID, //   MINUS \xa5
  State::INVALID, //   MINUS \xa6
  State::INVALID, //   MINUS \xa7
  State::INVALID, //   MINUS \xa8
  State::INVALID, //   MINUS \xa9
  State::INVALID, //   MINUS \xaa
  State::INVALID, //   MINUS \xab
  State::INVALID, //   MINUS \xac
  State::INVALID, //   MINUS \xad
  State::INVALID, //   MINUS \xae
  State::INVALID, //   MINUS \xaf
  State::INVALID, //   MINUS \xb0
  State::INVALID, //   MINUS \xb1
  State::INVALID, //   MINUS \xb2
  State::INVALID, //   MINUS \xb3
  State::INVALID, //   MINUS \xb4
  State::INVALID, //   MINUS \xb5
  State::INVALID, //   MINUS \xb6
  State::INVALID, //   MINUS \xb7
  State::INVALID, //   MINUS \xb8
  State::INVALID, //   MINUS \xb9
  State::INVALID, //   MINUS \xba
  State::INVALID, //   MINUS \xbb
  State::INVALID, //   MINUS \xbc
  State::INVALID, //   MINUS \xbd
  State::INVALID, //   MINUS \xbe
  State::INVALID, //   MINUS \xbf
  State::INVALID, //   MINUS \xc0
  State::INVALID, //   MINUS \xc1
  State::INVALID, //   MINUS \xc2
  State::INVALID, //   MINUS \xc3
  State::INVALID, //   MINUS \xc4
  State::INVALID, //   MINUS \xc5
  State::INVALID, //   MINUS \xc6
  State::INVALID, //   MINUS \xc7
  State::INVALID, //   MINUS \xc8
  State::INVALID, //   MINUS \xc9
  State::INVALID, //   MINUS \xca
  State::INVALID, //   MINUS \xcb
  State::INVALID, //   MINUS \xcc
  State::INVALID, //   MINUS \xcd
  State::INVALID, //   MINUS \xce
  State::INVALID, //   MINUS \xcf
  State::INVALID, //   MINUS \xd0
  State::INVALID, //   MINUS \xd1
  State::INVALID, //   MINUS \xd2
  State::INVALID, //   MINUS \xd3
  State::INVALID, //   MINUS \xd4
  State::INVALID, //   MINUS \xd5
  State::INVALID, //   MINUS \xd6
  State::INVALID, //   MINUS \xd7
  State::INVALID, //   MINUS \xd8
  State::INVALID, //   MINUS \xd9
  State::INVALID, //   MINUS \xda
  State::INVALID, //   MINUS \xdb
  State::INVALID, //   MINUS \xdc
  State::INVALID, //   MINUS \xdd
  State::INVALID, //   MINUS \xde
  State::INVALID, //   MINUS \xdf
  State::INVALID, //   MINUS \xe0
  State::INVALID, //   MINUS \xe1
  State::INVALID, //   MINUS \xe2
  State::INVALID, //   MINUS \xe3
  State::INVALID, //   MINUS \xe4
  State::INVALID, //   MINUS \xe5
  State::INVALID, //   MINUS \xe6
  State::INVALID, //   MINUS \xe7
  State::INVALID, //   MINUS \xe8
  State::INVALID, //   MINUS \xe9
  State::INVALID, //   MINUS \xea
  State::INVALID, //   MINUS \xeb
  State::INVALID, //   MINUS \xec
  State::INVALID, //   MINUS \xed
  State::INVALID, //   MINUS \xee
  State::INVALID, //   MINUS \xef
  State::INVALID, //   MINUS \xf0
  State::INVALID, //   MINUS \xf1
  State::INVALID, //   MINUS \xf2
  State::INVALID, //   MINUS \xf3
  State::INVALID, //   MINUS \xf4
  State::INVALID, //   MINUS \xf5
  State::INVALID, //   MINUS \xf6
  State::INVALID, //   MINUS \xf7
  State::INVALID, //   MINUS \xf8
  State::INVALID, //   MINUS \xf9
  State::INVALID, //   MINUS \xfa
  State::INVALID, //   MINUS \xfb
  State::INVALID, //   MINUS \xfc
  State::INVALID, //   MINUS \xfd
  State::INVALID, //   MINUS \xfe
  State::INVALID, //   MINUS \xff
  State::NEUTRAL, //   IN_NUMBER \x00
  State::NEUTRAL, //   IN_NUMBER \x01
  State::NEUTRAL, //   IN_NUMBER \x02
  State::NEUTRAL, //   IN_NUMBER \x03
  State::NEUTRAL, //   IN_NUMBER \x04
  State::NEUTRAL, //   IN_NUMBER \x05
  State::NEUTRAL, //   IN_NUMBER \x06
  State::NEUTRAL, //   IN_NUMBER \x07
  State::NEUTRAL, //   IN_NUMBER \x08
  State::NEUTRAL, //   IN_NUMBER \x09
  State::NEUTRAL, //   IN_NUMBER \x0a
  State::NEUTRAL, //   IN_NUMBER \x0b
  State::NEUTRAL, //   IN_NUMBER \x0c
  State::NEUTRAL, //   IN_NUMBER \x0d
  State::NEUTRAL, //   IN_NUMBER \x0e
  State::NEUTRAL, //   IN_NUMBER \x0f
  State::NEUTRAL, //   IN_NUMBER \x10
  State::NEUTRAL, //   IN_NUMBER \x11
  State::NEUTRAL, //   IN_NUMBER \x12
  State::NEUTRAL, //   IN_NUMBER \x13
  State::NEUTRAL, //   IN_NUMBER \x14
  State::NEUTRAL, //   IN_NUMBER \x15
  State::NEUTRAL, //   IN_NUMBER \x16
  State::NEUTRAL, //   IN_NUMBER \x17
  State::NEUTRAL, //   IN_NUMBER \x18
  State::NEUTRAL, //   IN_NUMBER \x19
  State::NEUTRAL, //   IN_NUMBER \x1a
  State::NEUTRAL, //   IN_NUMBER \x1b
  State::NEUTRAL, //   IN_NUMBER \x1c
  State::NEUTRAL, //   IN_NUMBER \x1d
  State::NEUTRAL, //   IN_NUMBER \x1e
  State::NEUTRAL, //   IN_NUMBER \x1f
  State::NEUTRAL, //   IN_NUMBER SPACE
  State::NEUTRAL, //   IN_NUMBER !
  State::NEUTRAL, //   IN_NUMBER \
  State::NEUTRAL, //   IN_NUMBER #
  State::NEUTRAL, //   IN_NUMBER $
  State::NEUTRAL, //   IN_NUMBER %
  State::NEUTRAL, //   IN_NUMBER &
  State::NEUTRAL, //   IN_NUMBER "
  State::NEUTRAL, //   IN_NUMBER (
  State::NEUTRAL, //   IN_NUMBER )
  State::NEUTRAL, //   IN_NUMBER *
  State::IN_NUMBER, // IN_NUMBER +
  State::NEUTRAL, //   IN_NUMBER ,
  State::IN_NUMBER, // IN_NUMBER -
  State::PERIOD, //    IN_NUMBER .
  State::NEUTRAL, //   IN_NUMBER /
  State::IN_NUMBER, // IN_NUMBER 0
  State::IN_NUMBER, // IN_NUMBER 1
  State::IN_NUMBER, // IN_NUMBER 2
  State::IN_NUMBER, // IN_NUMBER 3
  State::IN_NUMBER, // IN_NUMBER 4
  State::IN_NUMBER, // IN_NUMBER 5
  State::IN_NUMBER, // IN_NUMBER 6
  State::IN_NUMBER, // IN_NUMBER 7
  State::IN_NUMBER, // IN_NUMBER 8
  State::IN_NUMBER, // IN_NUMBER 9
  State::NEUTRAL, //   IN_NUMBER :
  State::NEUTRAL, //   IN_NUMBER ;
  State::NEUTRAL, //   IN_NUMBER <
  State::NEUTRAL, //   IN_NUMBER =
  State::NEUTRAL, //   IN_NUMBER >
  State::NEUTRAL, //   IN_NUMBER ?
  State::NEUTRAL, //   IN_NUMBER @
  State::NEUTRAL, //   IN_NUMBER A
  State::NEUTRAL, //   IN_NUMBER B
  State::NEUTRAL, //   IN_NUMBER C
  State::NEUTRAL, //   IN_NUMBER D
  State::IN_NUMBER, // IN_NUMBER E
  State::NEUTRAL, //   IN_NUMBER F
  State::NEUTRAL, //   IN_NUMBER G
  State::NEUTRAL, //   IN_NUMBER H
  State::NEUTRAL, //   IN_NUMBER I
  State::NEUTRAL, //   IN_NUMBER J
  State::NEUTRAL, //   IN_NUMBER K
  State::NEUTRAL, //   IN_NUMBER L
  State::NEUTRAL, //   IN_NUMBER M
  State::NEUTRAL, //   IN_NUMBER N
  State::NEUTRAL, //   IN_NUMBER O
  State::NEUTRAL, //   IN_NUMBER P
  State::NEUTRAL, //   IN_NUMBER Q
  State::NEUTRAL, //   IN_NUMBER R
  State::NEUTRAL, //   IN_NUMBER S
  State::NEUTRAL, //   IN_NUMBER T
  State::NEUTRAL, //   IN_NUMBER U
  State::NEUTRAL, //   IN_NUMBER V
  State::NEUTRAL, //   IN_NUMBER W
  State::NEUTRAL, //   IN_NUMBER X
  State::NEUTRAL, //   IN_NUMBER Y
  State::NEUTRAL, //   IN_NUMBER Z
  State::NEUTRAL, //   IN_NUMBER [
  State::NEUTRAL, //   IN_NUMBER \
  State::NEUTRAL, //   IN_NUMBER ]
  State::NEUTRAL, //   IN_NUMBER ^
  State::NEUTRAL, //   IN_NUMBER _
  State::NEUTRAL, //   IN_NUMBER `
  State::NEUTRAL, //   IN_NUMBER a
  State::NEUTRAL, //   IN_NUMBER b
  State::NEUTRAL, //   IN_NUMBER c
  State::NEUTRAL, //   IN_NUMBER d
  State::IN_NUMBER, // IN_NUMBER e
  State::NEUTRAL, //   IN_NUMBER f
  State::NEUTRAL, //   IN_NUMBER g
  State::NEUTRAL, //   IN_NUMBER h
  State::NEUTRAL, //   IN_NUMBER i
  State::NEUTRAL, //   IN_NUMBER j
  State::NEUTRAL, //   IN_NUMBER k
  State::NEUTRAL, //   IN_NUMBER l
  State::NEUTRAL, //   IN_NUMBER m
  State::NEUTRAL, //   IN_NUMBER n
  State::NEUTRAL, //   IN_NUMBER o
  State::NEUTRAL, //   IN_NUMBER p
  State::NEUTRAL, //   IN_NUMBER q
  State::NEUTRAL, //   IN_NUMBER r
  State::NEUTRAL, //   IN_NUMBER s
  State::NEUTRAL, //   IN_NUMBER t
  State::NEUTRAL, //   IN_NUMBER u
  State::NEUTRAL, //   IN_NUMBER v
  State::NEUTRAL, //   IN_NUMBER w
  State::NEUTRAL, //   IN_NUMBER x
  State::NEUTRAL, //   IN_NUMBER y
  State::NEUTRAL, //   IN_NUMBER z
  State::NEUTRAL, //   IN_NUMBER {
  State::NEUTRAL, //   IN_NUMBER |
  State::NEUTRAL, //   IN_NUMBER }
  State::NEUTRAL, //   IN_NUMBER ~
  State::NEUTRAL, //   IN_NUMBER \x7f
  State::NEUTRAL, //   IN_NUMBER \x80
  State::NEUTRAL, //   IN_NUMBER \x81
  State::NEUTRAL, //   IN_NUMBER \x82
  State::NEUTRAL, //   IN_NUMBER \x83
  State::NEUTRAL, //   IN_NUMBER \x84
  State::NEUTRAL, //   IN_NUMBER \x85
  State::NEUTRAL, //   IN_NUMBER \x86
  State::NEUTRAL, //   IN_NUMBER \x87
  State::NEUTRAL, //   IN_NUMBER \x88
  State::NEUTRAL, //   IN_NUMBER \x89
  State::NEUTRAL, //   IN_NUMBER \x8a
  State::NEUTRAL, //   IN_NUMBER \x8b
  State::NEUTRAL, //   IN_NUMBER \x8c
  State::NEUTRAL, //   IN_NUMBER \x8d
  State::NEUTRAL, //   IN_NUMBER \x8e
  State::NEUTRAL, //   IN_NUMBER \x8f
  State::NEUTRAL, //   IN_NUMBER \x90
  State::NEUTRAL, //   IN_NUMBER \x91
  State::NEUTRAL, //   IN_NUMBER \x92
  State::NEUTRAL, //   IN_NUMBER \x93
  State::NEUTRAL, //   IN_NUMBER \x94
  State::NEUTRAL, //   IN_NUMBER \x95
  State::NEUTRAL, //   IN_NUMBER \x96
  State::NEUTRAL, //   IN_NUMBER \x97
  State::NEUTRAL, //   IN_NUMBER \x98
  State::NEUTRAL, //   IN_NUMBER \x99
  State::NEUTRAL, //   IN_NUMBER \x9a
  State::NEUTRAL, //   IN_NUMBER \x9b
  State::NEUTRAL, //   IN_NUMBER \x9c
  State::NEUTRAL, //   IN_NUMBER \x9d
  State::NEUTRAL, //   IN_NUMBER \x9e
  State::NEUTRAL, //   IN_NUMBER \x9f
  State::NEUTRAL, //   IN_NUMBER \xa0
  State::NEUTRAL, //   IN_NUMBER \xa1
  State::NEUTRAL, //   IN_NUMBER \xa2
  State::NEUTRAL, //   IN_NUMBER \xa3
  State::NEUTRAL, //   IN_NUMBER \xa4
  State::NEUTRAL, //   IN_NUMBER \xa5
  State::NEUTRAL, //   IN_NUMBER \xa6
  State::NEUTRAL, //   IN_NUMBER \xa7
  State::NEUTRAL, //   IN_NUMBER \xa8
  State::NEUTRAL, //   IN_NUMBER \xa9
  State::NEUTRAL, //   IN_NUMBER \xaa
  State::NEUTRAL, //   IN_NUMBER \xab
  State::NEUTRAL, //   IN_NUMBER \xac
  State::NEUTRAL, //   IN_NUMBER \xad
  State::NEUTRAL, //   IN_NUMBER \xae
  State::NEUTRAL, //   IN_NUMBER \xaf
  State::NEUTRAL, //   IN_NUMBER \xb0
  State::NEUTRAL, //   IN_NUMBER \xb1
  State::NEUTRAL, //   IN_NUMBER \xb2
  State::NEUTRAL, //   IN_NUMBER \xb3
  State::NEUTRAL, //   IN_NUMBER \xb4
  State::NEUTRAL, //   IN_NUMBER \xb5
  State::NEUTRAL, //   IN_NUMBER \xb6
  State::NEUTRAL, //   IN_NUMBER \xb7
  State::NEUTRAL, //   IN_NUMBER \xb8
  State::NEUTRAL, //   IN_NUMBER \xb9
  State::NEUTRAL, //   IN_NUMBER \xba
  State::NEUTRAL, //   IN_NUMBER \xbb
  State::NEUTRAL, //   IN_NUMBER \xbc
  State::NEUTRAL, //   IN_NUMBER \xbd
  State::NEUTRAL, //   IN_NUMBER \xbe
  State::NEUTRAL, //   IN_NUMBER \xbf
  State::NEUTRAL, //   IN_NUMBER \xc0
  State::NEUTRAL, //   IN_NUMBER \xc1
  State::NEUTRAL, //   IN_NUMBER \xc2
  State::NEUTRAL, //   IN_NUMBER \xc3
  State::NEUTRAL, //   IN_NUMBER \xc4
  State::NEUTRAL, //   IN_NUMBER \xc5
  State::NEUTRAL, //   IN_NUMBER \xc6
  State::NEUTRAL, //   IN_NUMBER \xc7
  State::NEUTRAL, //   IN_NUMBER \xc8
  State::NEUTRAL, //   IN_NUMBER \xc9
  State::NEUTRAL, //   IN_NUMBER \xca
  State::NEUTRAL, //   IN_NUMBER \xcb
  State::NEUTRAL, //   IN_NUMBER \xcc
  State::NEUTRAL, //   IN_NUMBER \xcd
  State::NEUTRAL, //   IN_NUMBER \xce
  State::NEUTRAL, //   IN_NUMBER \xcf
  State::NEUTRAL, //   IN_NUMBER \xd0
  State::NEUTRAL, //   IN_NUMBER \xd1
  State::NEUTRAL, //   IN_NUMBER \xd2
  State::NEUTRAL, //   IN_NUMBER \xd3
  State::NEUTRAL, //   IN_NUMBER \xd4
  State::NEUTRAL, //   IN_NUMBER \xd5
  State::NEUTRAL, //   IN_NUMBER \xd6
  State::NEUTRAL, //   IN_NUMBER \xd7
  State::NEUTRAL, //   IN_NUMBER \xd8
  State::NEUTRAL, //   IN_NUMBER \xd9
  State::NEUTRAL, //   IN_NUMBER \xda
  State::NEUTRAL, //   IN_NUMBER \xdb
  State::NEUTRAL, //   IN_NUMBER \xdc
  State::NEUTRAL, //   IN_NUMBER \xdd
  State::NEUTRAL, //   IN_NUMBER \xde
  State::NEUTRAL, //   IN_NUMBER \xdf
  State::NEUTRAL, //   IN_NUMBER \xe0
  State::NEUTRAL, //   IN_NUMBER \xe1
  State::NEUTRAL, //   IN_NUMBER \xe2
  State::NEUTRAL, //   IN_NUMBER \xe3
  State::NEUTRAL, //   IN_NUMBER \xe4
  State::NEUTRAL, //   IN_NUMBER \xe5
  State::NEUTRAL, //   IN_NUMBER \xe6
  State::NEUTRAL, //   IN_NUMBER \xe7
  State::NEUTRAL, //   IN_NUMBER \xe8
  State::NEUTRAL, //   IN_NUMBER \xe9
  State::NEUTRAL, //   IN_NUMBER \xea
  State::NEUTRAL, //   IN_NUMBER \xeb
  State::NEUTRAL, //   IN_NUMBER \xec
  State::NEUTRAL, //   IN_NUMBER \xed
  State::NEUTRAL, //   IN_NUMBER \xee
  State::NEUTRAL, //   IN_NUMBER \xef
  State::NEUTRAL, //   IN_NUMBER \xf0
  State::NEUTRAL, //   IN_NUMBER \xf1
  State::NEUTRAL, //   IN_NUMBER \xf2
  State::NEUTRAL, //   IN_NUMBER \xf3
  State::NEUTRAL, //   IN_NUMBER \xf4
  State::NEUTRAL, //   IN_NUMBER \xf5
  State::NEUTRAL, //   IN_NUMBER \xf6
  State::NEUTRAL, //   IN_NUMBER \xf7
  State::NEUTRAL, //   IN_NUMBER \xf8
  State::NEUTRAL, //   IN_NUMBER \xf9
  State::NEUTRAL, //   IN_NUMBER \xfa
  State::NEUTRAL, //   IN_NUMBER \xfb
  State::NEUTRAL, //   IN_NUMBER \xfc
  State::NEUTRAL, //   IN_NUMBER \xfd
  State::NEUTRAL, //   IN_NUMBER \xfe
  State::NEUTRAL, //   IN_NUMBER \xff
  State::INVALID, //   PERIOD \x00
  State::INVALID, //   PERIOD \x01
  State::INVALID, //   PERIOD \x02
  State::INVALID, //   PERIOD \x03
  State::INVALID, //   PERIOD \x04
  State::INVALID, //   PERIOD \x05
  State::INVALID, //   PERIOD \x06
  State::INVALID, //   PERIOD \x07
  State::INVALID, //   PERIOD \x08
  State::INVALID, //   PERIOD \x09
  State::INVALID, //   PERIOD \x0a
  State::INVALID, //   PERIOD \x0b
  State::INVALID, //   PERIOD \x0c
  State::INVALID, //   PERIOD \x0d
  State::INVALID, //   PERIOD \x0e
  State::INVALID, //   PERIOD \x0f
  State::INVALID, //   PERIOD \x10
  State::INVALID, //   PERIOD \x11
  State::INVALID, //   PERIOD \x12
  State::INVALID, //   PERIOD \x13
  State::INVALID, //   PERIOD \x14
  State::INVALID, //   PERIOD \x15
  State::INVALID, //   PERIOD \x16
  State::INVALID, //   PERIOD \x17
  State::INVALID, //   PERIOD \x18
  State::INVALID, //   PERIOD \x19
  State::INVALID, //   PERIOD \x1a
  State::INVALID, //   PERIOD \x1b
  State::INVALID, //   PERIOD \x1c
  State::INVALID, //   PERIOD \x1d
  State::INVALID, //   PERIOD \x1e
  State::INVALID, //   PERIOD \x1f
  State::INVALID, //   PERIOD SPACE
  State::INVALID, //   PERIOD !
  State::INVALID, //   PERIOD \
  State::INVALID, //   PERIOD #
  State::INVALID, //   PERIOD $
  State::INVALID, //   PERIOD %
  State::INVALID, //   PERIOD &
  State::INVALID, //   PERIOD "
  State::INVALID, //   PERIOD (
  State::INVALID, //   PERIOD )
  State::INVALID, //   PERIOD *
  State::INVALID, //   PERIOD +
  State::INVALID, //   PERIOD ,
  State::INVALID, //   PERIOD -
  State::INVALID, //   PERIOD .
  State::INVALID, //   PERIOD /
  State::IN_NUMBER, // PERIOD 0
  State::IN_NUMBER, // PERIOD 1
  State::IN_NUMBER, // PERIOD 2
  State::IN_NUMBER, // PERIOD 3
  State::IN_NUMBER, // PERIOD 4
  State::IN_NUMBER, // PERIOD 5
  State::IN_NUMBER, // PERIOD 6
  State::IN_NUMBER, // PERIOD 7
  State::IN_NUMBER, // PERIOD 8
  State::IN_NUMBER, // PERIOD 9
  State::INVALID, //   PERIOD :
  State::INVALID, //   PERIOD ;
  State::INVALID, //   PERIOD <
  State::INVALID, //   PERIOD =
  State::INVALID, //   PERIOD >
  State::INVALID, //   PERIOD ?
  State::INVALID, //   PERIOD @
  State::INVALID, //   PERIOD A
  State::INVALID, //   PERIOD B
  State::INVALID, //   PERIOD C
  State::INVALID, //   PERIOD D
  State::INVALID, //   PERIOD E
  State::INVALID, //   PERIOD F
  State::INVALID, //   PERIOD G
  State::INVALID, //   PERIOD H
  State::INVALID, //   PERIOD I
  State::INVALID, //   PERIOD J
  State::INVALID, //   PERIOD K
  State::INVALID, //   PERIOD L
  State::INVALID, //   PERIOD M
  State::INVALID, //   PERIOD N
  State::INVALID, //   PERIOD O
  State::INVALID, //   PERIOD P
  State::INVALID, //   PERIOD Q
  State::INVALID, //   PERIOD R
  State::INVALID, //   PERIOD S
  State::INVALID, //   PERIOD T
  State::INVALID, //   PERIOD U
  State::INVALID, //   PERIOD V
  State::INVALID, //   PERIOD W
  State::INVALID, //   PERIOD X
  State::INVALID, //   PERIOD Y
  State::INVALID, //   PERIOD Z
  State::INVALID, //   PERIOD [
  State::INVALID, //   PERIOD \
  State::INVALID, //   PERIOD ]
  State::INVALID, //   PERIOD ^
  State::INVALID, //   PERIOD _
  State::INVALID, //   PERIOD `
  State::INVALID, //   PERIOD a
  State::INVALID, //   PERIOD b
  State::INVALID, //   PERIOD c
  State::INVALID, //   PERIOD d
  State::INVALID, //   PERIOD e
  State::INVALID, //   PERIOD f
  State::INVALID, //   PERIOD g
  State::INVALID, //   PERIOD h
  State::INVALID, //   PERIOD i
  State::INVALID, //   PERIOD j
  State::INVALID, //   PERIOD k
  State::INVALID, //   PERIOD l
  State::INVALID, //   PERIOD m
  State::INVALID, //   PERIOD n
  State::INVALID, //   PERIOD o
  State::INVALID, //   PERIOD p
  State::INVALID, //   PERIOD q
  State::INVALID, //   PERIOD r
  State::INVALID, //   PERIOD s
  State::INVALID, //   PERIOD t
  State::INVALID, //   PERIOD u
  State::INVALID, //   PERIOD v
  State::INVALID, //   PERIOD w
  State::INVALID, //   PERIOD x
  State::INVALID, //   PERIOD y
  State::INVALID, //   PERIOD z
  State::INVALID, //   PERIOD {
  State::INVALID, //   PERIOD |
  State::INVALID, //   PERIOD }
  State::INVALID, //   PERIOD ~
  State::INVALID, //   PERIOD \x7f
  State::INVALID, //   PERIOD \x80
  State::INVALID, //   PERIOD \x81
  State::INVALID, //   PERIOD \x82
  State::INVALID, //   PERIOD \x83
  State::INVALID, //   PERIOD \x84
  State::INVALID, //   PERIOD \x85
  State::INVALID, //   PERIOD \x86
  State::INVALID, //   PERIOD \x87
  State::INVALID, //   PERIOD \x88
  State::INVALID, //   PERIOD \x89
  State::INVALID, //   PERIOD \x8a
  State::INVALID, //   PERIOD \x8b
  State::INVALID, //   PERIOD \x8c
  State::INVALID, //   PERIOD \x8d
  State::INVALID, //   PERIOD \x8e
  State::INVALID, //   PERIOD \x8f
  State::INVALID, //   PERIOD \x90
  State::INVALID, //   PERIOD \x91
  State::INVALID, //   PERIOD \x92
  State::INVALID, //   PERIOD \x93
  State::INVALID, //   PERIOD \x94
  State::INVALID, //   PERIOD \x95
  State::INVALID, //   PERIOD \x96
  State::INVALID, //   PERIOD \x97
  State::INVALID, //   PERIOD \x98
  State::INVALID, //   PERIOD \x99
  State::INVALID, //   PERIOD \x9a
  State::INVALID, //   PERIOD \x9b
  State::INVALID, //   PERIOD \x9c
  State::INVALID, //   PERIOD \x9d
  State::INVALID, //   PERIOD \x9e
  State::INVALID, //   PERIOD \x9f
  State::INVALID, //   PERIOD \xa0
  State::INVALID, //   PERIOD \xa1
  State::INVALID, //   PERIOD \xa2
  State::INVALID, //   PERIOD \xa3
  State::INVALID, //   PERIOD \xa4
  State::INVALID, //   PERIOD \xa5
  State::INVALID, //   PERIOD \xa6
  State::INVALID, //   PERIOD \xa7
  State::INVALID, //   PERIOD \xa8
  State::INVALID, //   PERIOD \xa9
  State::INVALID, //   PERIOD \xaa
  State::INVALID, //   PERIOD \xab
  State::INVALID, //   PERIOD \xac
  State::INVALID, //   PERIOD \xad
  State::INVALID, //   PERIOD \xae
  State::INVALID, //   PERIOD \xaf
  State::INVALID, //   PERIOD \xb0
  State::INVALID, //   PERIOD \xb1
  State::INVALID, //   PERIOD \xb2
  State::INVALID, //   PERIOD \xb3
  State::INVALID, //   PERIOD \xb4
  State::INVALID, //   PERIOD \xb5
  State::INVALID, //   PERIOD \xb6
  State::INVALID, //   PERIOD \xb7
  State::INVALID, //   PERIOD \xb8
  State::INVALID, //   PERIOD \xb9
  State::INVALID, //   PERIOD \xba
  State::INVALID, //   PERIOD \xbb
  State::INVALID, //   PERIOD \xbc
  State::INVALID, //   PERIOD \xbd
  State::INVALID, //   PERIOD \xbe
  State::INVALID, //   PERIOD \xbf
  State::INVALID, //   PERIOD \xc0
  State::INVALID, //   PERIOD \xc1
  State::INVALID, //   PERIOD \xc2
  State::INVALID, //   PERIOD \xc3
  State::INVALID, //   PERIOD \xc4
  State::INVALID, //   PERIOD \xc5
  State::INVALID, //   PERIOD \xc6
  State::INVALID, //   PERIOD \xc7
  State::INVALID, //   PERIOD \xc8
  State::INVALID, //   PERIOD \xc9
  State::INVALID, //   PERIOD \xca
  State::INVALID, //   PERIOD \xcb
  State::INVALID, //   PERIOD \xcc
  State::INVALID, //   PERIOD \xcd
  State::INVALID, //   PERIOD \xce
  State::INVALID, //   PERIOD \xcf
  State::INVALID, //   PERIOD \xd0
  State::INVALID, //   PERIOD \xd1
  State::INVALID, //   PERIOD \xd2
  State::INVALID, //   PERIOD \xd3
  State::INVALID, //   PERIOD \xd4
  State::INVALID, //   PERIOD \xd5
  State::INVALID, //   PERIOD \xd6
  State::INVALID, //   PERIOD \xd7
  State::INVALID, //   PERIOD \xd8
  State::INVALID, //   PERIOD \xd9
  State::INVALID, //   PERIOD \xda
  State::INVALID, //   PERIOD \xdb
  State::INVALID, //   PERIOD \xdc
  State::INVALID, //   PERIOD \xdd
  State::INVALID, //   PERIOD \xde
  State::INVALID, //   PERIOD \xdf
  State::INVALID, //   PERIOD \xe0
  State::INVALID, //   PERIOD \xe1
  State::INVALID, //   PERIOD \xe2
  State::INVALID, //   PERIOD \xe3
  State::INVALID, //   PERIOD \xe4
  State::INVALID, //   PERIOD \xe5
  State::INVALID, //   PERIOD \xe6
  State::INVALID, //   PERIOD \xe7
  State::INVALID, //   PERIOD \xe8
  State::INVALID, //   PERIOD \xe9
  State::INVALID, //   PERIOD \xea
  State::INVALID, //   PERIOD \xeb
  State::INVALID, //   PERIOD \xec
  State::INVALID, //   PERIOD \xed
  State::INVALID, //   PERIOD \xee
  State::INVALID, //   PERIOD \xef
  State::INVALID, //   PERIOD \xf0
  State::INVALID, //   PERIOD \xf1
  State::INVALID, //   PERIOD \xf2
  State::INVALID, //   PERIOD \xf3
  State::INVALID, //   PERIOD \xf4
  State::INVALID, //   PERIOD \xf5
  State::INVALID, //   PERIOD \xf6
  State::INVALID, //   PERIOD \xf7
  State::INVALID, //   PERIOD \xf8
  State::INVALID, //   PERIOD \xf9
  State::INVALID, //   PERIOD \xfa
  State::INVALID, //   PERIOD \xfb
  State::INVALID, //   PERIOD \xfc
  State::INVALID, //   PERIOD \xfd
  State::INVALID, //   PERIOD \xfe
  State::INVALID, //   PERIOD \xff
  State::INVALID, //   INITIAL \x00
  State::INVALID, //   INITIAL \x01
  State::INVALID, //   INITIAL \x02
  State::INVALID, //   INITIAL \x03
  State::INVALID, //   INITIAL \x04
  State::INVALID, //   INITIAL \x05
  State::INVALID, //   INITIAL \x06
  State::INVALID, //   INITIAL \x07
  State::INVALID, //   INITIAL \x08
  State::INITIAL, //   INITIAL \x09
  State::INITIAL, //   INITIAL \x0a
  State::INVALID, //   INITIAL \x0b
  State::INVALID, //   INITIAL \x0c
  State::INITIAL, //   INITIAL \x0d
  State::INVALID, //   INITIAL \x0e
  State::INVALID, //   INITIAL \x0f
  State::INVALID, //   INITIAL \x10
  State::INVALID, //   INITIAL \x11
  State::INVALID, //   INITIAL \x12
  State::INVALID, //   INITIAL \x13
  State::INVALID, //   INITIAL \x14
  State::INVALID, //   INITIAL \x15
  State::INVALID, //   INITIAL \x16
  State::INVALID, //   INITIAL \x17
  State::INVALID, //   INITIAL \x18
  State::INVALID, //   INITIAL \x19
  State::INVALID, //   INITIAL \x1a
  State::INVALID, //   INITIAL \x1b
  State::INVALID, //   INITIAL \x1c
  State::INVALID, //   INITIAL \x1d
  State::INVALID, //   INITIAL \x1e
  State::INVALID, //   INITIAL \x1f
  State::INITIAL, //   INITIAL SPACE
  State::INVALID, //   INITIAL !
  State::IN_STRING, // INITIAL \
  State::INVALID, //   INITIAL #
  State::INVALID, //   INITIAL $
  State::INVALID, //   INITIAL %
  State::INVALID, //   INITIAL &
  State::INVALID, //   INITIAL "
  State::INVALID, //   INITIAL (
  State::INVALID, //   INITIAL )
  State::INVALID, //   INITIAL *
  State::INVALID, //   INITIAL +
  State::NEUTRAL, //   INITIAL ,
  State::MINUS, //     INITIAL -
  State::INVALID, //   INITIAL .
  State::INVALID, //   INITIAL /
  State::IN_NUMBER, // INITIAL 0
  State::IN_NUMBER, // INITIAL 1
  State::IN_NUMBER, // INITIAL 2
  State::IN_NUMBER, // INITIAL 3
  State::IN_NUMBER, // INITIAL 4
  State::IN_NUMBER, // INITIAL 5
  State::IN_NUMBER, // INITIAL 6
  State::IN_NUMBER, // INITIAL 7
  State::IN_NUMBER, // INITIAL 8
  State::IN_NUMBER, // INITIAL 9
  State::NEUTRAL, //   INITIAL :
  State::INVALID, //   INITIAL ;
  State::INVALID, //   INITIAL <
  State::INVALID, //   INITIAL =
  State::INVALID, //   INITIAL >
  State::INVALID, //   INITIAL ?
  State::INVALID, //   INITIAL @
  State::INVALID, //   INITIAL A
  State::INVALID, //   INITIAL B
  State::INVALID, //   INITIAL C
  State::INVALID, //   INITIAL D
  State::INVALID, //   INITIAL E
  State::INVALID, //   INITIAL F
  State::INVALID, //   INITIAL G
  State::INVALID, //   INITIAL H
  State::INVALID, //   INITIAL I
  State::INVALID, //   INITIAL J
  State::INVALID, //   INITIAL K
  State::INVALID, //   INITIAL L
  State::INVALID, //   INITIAL M
  State::INVALID, //   INITIAL N
  State::INVALID, //   INITIAL O
  State::INVALID, //   INITIAL P
  State::INVALID, //   INITIAL Q
  State::INVALID, //   INITIAL R
  State::INVALID, //   INITIAL S
  State::INVALID, //   INITIAL T
  State::INVALID, //   INITIAL U
  State::INVALID, //   INITIAL V
  State::INVALID, //   INITIAL W
  State::INVALID, //   INITIAL X
  State::INVALID, //   INITIAL Y
  State::INVALID, //   INITIAL Z
  State::NEUTRAL, //   INITIAL [
  State::INVALID, //   INITIAL \
  State::NEUTRAL, //   INITIAL ]
  State::INVALID, //   INITIAL ^
  State::INVALID, //   INITIAL _
  State::INVALID, //   INITIAL `
  State::NEUTRAL, //   INITIAL a
  State::INVALID, //   INITIAL b
  State::INVALID, //   INITIAL c
  State::INVALID, //   INITIAL d
  State::NEUTRAL, //   INITIAL e
  State::NEUTRAL, //   INITIAL f
  State::INVALID, //   INITIAL g
  State::INVALID, //   INITIAL h
  State::INVALID, //   INITIAL i
  State::INVALID, //   INITIAL j
  State::INVALID, //   INITIAL k
  State::NEUTRAL, //   INITIAL l
  State::INVALID, //   INITIAL m
  State::NEUTRAL, //   INITIAL n
  State::INVALID, //   INITIAL o
  State::INVALID, //   INITIAL p
  State::INVALID, //   INITIAL q
  State::NEUTRAL, //   INITIAL r
  State::NEUTRAL, //   INITIAL s
  State::NEUTRAL, //   INITIAL t
  State::NEUTRAL, //   INITIAL u
  State::INVALID, //   INITIAL v
  State::INVALID, //   INITIAL w
  State::INVALID, //   INITIAL x
  State::INVALID, //   INITIAL y
  State::INVALID, //   INITIAL z
  State::NEUTRAL, //   INITIAL {
  State::INVALID, //   INITIAL |
  State::NEUTRAL, //   INITIAL }
  State::INVALID, //   INITIAL ~
  State::INVALID, //   INITIAL \x7f
  State::INVALID, //   INITIAL \x80
  State::INVALID, //   INITIAL \x81
  State::INVALID, //   INITIAL \x82
  State::INVALID, //   INITIAL \x83
  State::INVALID, //   INITIAL \x84
  State::INVALID, //   INITIAL \x85
  State::INVALID, //   INITIAL \x86
  State::INVALID, //   INITIAL \x87
  State::INVALID, //   INITIAL \x88
  State::INVALID, //   INITIAL \x89
  State::INVALID, //   INITIAL \x8a
  State::INVALID, //   INITIAL \x8b
  State::INVALID, //   INITIAL \x8c
  State::INVALID, //   INITIAL \x8d
  State::INVALID, //   INITIAL \x8e
  State::INVALID, //   INITIAL \x8f
  State::INVALID, //   INITIAL \x90
  State::INVALID, //   INITIAL \x91
  State::INVALID, //   INITIAL \x92
  State::INVALID, //   INITIAL \x93
  State::INVALID, //   INITIAL \x94
  State::INVALID, //   INITIAL \x95
  State::INVALID, //   INITIAL \x96
  State::INVALID, //   INITIAL \x97
  State::INVALID, //   INITIAL \x98
  State::INVALID, //   INITIAL \x99
  State::INVALID, //   INITIAL \x9a
  State::INVALID, //   INITIAL \x9b
  State::INVALID, //   INITIAL \x9c
  State::INVALID, //   INITIAL \x9d
  State::INVALID, //   INITIAL \x9e
  State::INVALID, //   INITIAL \x9f
  State::INVALID, //   INITIAL \xa0
  State::INVALID, //   INITIAL \xa1
  State::INVALID, //   INITIAL \xa2
  State::INVALID, //   INITIAL \xa3
  State::INVALID, //   INITIAL \xa4
  State::INVALID, //   INITIAL \xa5
  State::INVALID, //   INITIAL \xa6
  State::INVALID, //   INITIAL \xa7
  State::INVALID, //   INITIAL \xa8
  State::INVALID, //   INITIAL \xa9
  State::INVALID, //   INITIAL \xaa
  State::INVALID, //   INITIAL \xab
  State::INVALID, //   INITIAL \xac
  State::INVALID, //   INITIAL \xad
  State::INVALID, //   INITIAL \xae
  State::INVALID, //   INITIAL \xaf
  State::INVALID, //   INITIAL \xb0
  State::INVALID, //   INITIAL \xb1
  State::INVALID, //   INITIAL \xb2
  State::INVALID, //   INITIAL \xb3
  State::INVALID, //   INITIAL \xb4
  State::INVALID, //   INITIAL \xb5
  State::INVALID, //   INITIAL \xb6
  State::INVALID, //   INITIAL \xb7
  State::INVALID, //   INITIAL \xb8
  State::INVALID, //   INITIAL \xb9
  State::INVALID, //   INITIAL \xba
  State::INVALID, //   INITIAL \xbb
  State::INVALID, //   INITIAL \xbc
  State::INVALID, //   INITIAL \xbd
  State::INVALID, //   INITIAL \xbe
  State::INVALID, //   INITIAL \xbf
  State::INVALID, //   INITIAL \xc0
  State::INVALID, //   INITIAL \xc1
  State::INVALID, //   INITIAL \xc2
  State::INVALID, //   INITIAL \xc3
  State::INVALID, //   INITIAL \xc4
  State::INVALID, //   INITIAL \xc5
  State::INVALID, //   INITIAL \xc6
  State::INVALID, //   INITIAL \xc7
  State::INVALID, //   INITIAL \xc8
  State::INVALID, //   INITIAL \xc9
  State::INVALID, //   INITIAL \xca
  State::INVALID, //   INITIAL \xcb
  State::INVALID, //   INITIAL \xcc
  State::INVALID, //   INITIAL \xcd
  State::INVALID, //   INITIAL \xce
  State::INVALID, //   INITIAL \xcf
  State::INVALID, //   INITIAL \xd0
  State::INVALID, //   INITIAL \xd1
  State::INVALID, //   INITIAL \xd2
  State::INVALID, //   INITIAL \xd3
  State::INVALID, //   INITIAL \xd4
  State::INVALID, //   INITIAL \xd5
  State::INVALID, //   INITIAL \xd6
  State::INVALID, //   INITIAL \xd7
  State::INVALID, //   INITIAL \xd8
  State::INVALID, //   INITIAL \xd9
  State::INVALID, //   INITIAL \xda
  State::INVALID, //   INITIAL \xdb
  State::INVALID, //   INITIAL \xdc
  State::INVALID, //   INITIAL \xdd
  State::INVALID, //   INITIAL \xde
  State::INVALID, //   INITIAL \xdf
  State::INVALID, //   INITIAL \xe0
  State::INVALID, //   INITIAL \xe1
  State::INVALID, //   INITIAL \xe2
  State::INVALID, //   INITIAL \xe3
  State::INVALID, //   INITIAL \xe4
  State::INVALID, //   INITIAL \xe5
  State::INVALID, //   INITIAL \xe6
  State::INVALID, //   INITIAL \xe7
  State::INVALID, //   INITIAL \xe8
  State::INVALID, //   INITIAL \xe9
  State::INVALID, //   INITIAL \xea
  State::INVALID, //   INITIAL \xeb
  State::INVALID, //   INITIAL \xec
  State::INVALID, //   INITIAL \xed
  State::INVALID, //   INITIAL \xee
  State::INVALID, //   INITIAL \xef
  State::INVALID, //   INITIAL \xf0
  State::INVALID, //   INITIAL \xf1
  State::INVALID, //   INITIAL \xf2
  State::INVALID, //   INITIAL \xf3
  State::INVALID, //   INITIAL \xf4
  State::INVALID, //   INITIAL \xf5
  State::INVALID, //   INITIAL \xf6
  State::INVALID, //   INITIAL \xf7
  State::INVALID, //   INITIAL \xf8
  State::INVALID, //   INITIAL \xf9
  State::INVALID, //   INITIAL \xfa
  State::INVALID, //   INITIAL \xfb
  State::INVALID, //   INITIAL \xfc
  State::INVALID, //   INITIAL \xfd
  State::INVALID, //   INITIAL \xfe
  State::INVALID, //   INITIAL \xff
  State::INVALID, //   INVALID \x00
  State::INVALID, //   INVALID \x01
  State::INVALID, //   INVALID \x02
  State::INVALID, //   INVALID \x03
  State::INVALID, //   INVALID \x04
  State::INVALID, //   INVALID \x05
  State::INVALID, //   INVALID \x06
  State::INVALID, //   INVALID \x07
  State::INVALID, //   INVALID \x08
  State::INVALID, //   INVALID \x09
  State::INVALID, //   INVALID \x0a
  State::INVALID, //   INVALID \x0b
  State::INVALID, //   INVALID \x0c
  State::INVALID, //   INVALID \x0d
  State::INVALID, //   INVALID \x0e
  State::INVALID, //   INVALID \x0f
  State::INVALID, //   INVALID \x10
  State::INVALID, //   INVALID \x11
  State::INVALID, //   INVALID \x12
  State::INVALID, //   INVALID \x13
  State::INVALID, //   INVALID \x14
  State::INVALID, //   INVALID \x15
  State::INVALID, //   INVALID \x16
  State::INVALID, //   INVALID \x17
  State::INVALID, //   INVALID \x18
  State::INVALID, //   INVALID \x19
  State::INVALID, //   INVALID \x1a
  State::INVALID, //   INVALID \x1b
  State::INVALID, //   INVALID \x1c
  State::INVALID, //   INVALID \x1d
  State::INVALID, //   INVALID \x1e
  State::INVALID, //   INVALID \x1f
  State::INVALID, //   INVALID SPACE
  State::INVALID, //   INVALID !
  State::INVALID, //   INVALID \
  State::INVALID, //   INVALID #
  State::INVALID, //   INVALID $
  State::INVALID, //   INVALID %
  State::INVALID, //   INVALID &
  State::INVALID, //   INVALID "
  State::INVALID, //   INVALID (
  State::INVALID, //   INVALID )
  State::INVALID, //   INVALID *
  State::INVALID, //   INVALID +
  State::INVALID, //   INVALID ,
  State::INVALID, //   INVALID -
  State::INVALID, //   INVALID .
  State::INVALID, //   INVALID /
  State::INVALID, //   INVALID 0
  State::INVALID, //   INVALID 1
  State::INVALID, //   INVALID 2
  State::INVALID, //   INVALID 3
  State::INVALID, //   INVALID 4
  State::INVALID, //   INVALID 5
  State::INVALID, //   INVALID 6
  State::INVALID, //   INVALID 7
  State::INVALID, //   INVALID 8
  State::INVALID, //   INVALID 9
  State::INVALID, //   INVALID :
  State::INVALID, //   INVALID ;
  State::INVALID, //   INVALID <
  State::INVALID, //   INVALID =
  State::INVALID, //   INVALID >
  State::INVALID, //   INVALID ?
  State::INVALID, //   INVALID @
  State::INVALID, //   INVALID A
  State::INVALID, //   INVALID B
  State::INVALID, //   INVALID C
  State::INVALID, //   INVALID D
  State::INVALID, //   INVALID E
  State::INVALID, //   INVALID F
  State::INVALID, //   INVALID G
  State::INVALID, //   INVALID H
  State::INVALID, //   INVALID I
  State::INVALID, //   INVALID J
  State::INVALID, //   INVALID K
  State::INVALID, //   INVALID L
  State::INVALID, //   INVALID M
  State::INVALID, //   INVALID N
  State::INVALID, //   INVALID O
  State::INVALID, //   INVALID P
  State::INVALID, //   INVALID Q
  State::INVALID, //   INVALID R
  State::INVALID, //   INVALID S
  State::INVALID, //   INVALID T
  State::INVALID, //   INVALID U
  State::INVALID, //   INVALID V
  State::INVALID, //   INVALID W
  State::INVALID, //   INVALID X
  State::INVALID, //   INVALID Y
  State::INVALID, //   INVALID Z
  State::INVALID, //   INVALID [
  State::INVALID, //   INVALID \
  State::INVALID, //   INVALID ]
  State::INVALID, //   INVALID ^
  State::INVALID, //   INVALID _
  State::INVALID, //   INVALID `
  State::INVALID, //   INVALID a
  State::INVALID, //   INVALID b
  State::INVALID, //   INVALID c
  State::INVALID, //   INVALID d
  State::INVALID, //   INVALID e
  State::INVALID, //   INVALID f
  State::INVALID, //   INVALID g
  State::INVALID, //   INVALID h
  State::INVALID, //   INVALID i
  State::INVALID, //   INVALID j
  State::INVALID, //   INVALID k
  State::INVALID, //   INVALID l
  State::INVALID, //   INVALID m
  State::INVALID, //   INVALID n
  State::INVALID, //   INVALID o
  State::INVALID, //   INVALID p
  State::INVALID, //   INVALID q
  State::INVALID, //   INVALID r
  State::INVALID, //   INVALID s
  State::INVALID, //   INVALID t
  State::INVALID, //   INVALID u
  State::INVALID, //   INVALID v
  State::INVALID, //   INVALID w
  State::INVALID, //   INVALID x
  State::INVALID, //   INVALID y
  State::INVALID, //   INVALID z
  State::INVALID, //   INVALID {
  State::INVALID, //   INVALID |
  State::INVALID, //   INVALID }
  State::INVALID, //   INVALID ~
  State::INVALID, //   INVALID \x7f
  State::INVALID, //   INVALID \x80
  State::INVALID, //   INVALID \x81
  State::INVALID, //   INVALID \x82
  State::INVALID, //   INVALID \x83
  State::INVALID, //   INVALID \x84
  State::INVALID, //   INVALID \x85
  State::INVALID, //   INVALID \x86
  State::INVALID, //   INVALID \x87
  State::INVALID, //   INVALID \x88
  State::INVALID, //   INVALID \x89
  State::INVALID, //   INVALID \x8a
  State::INVALID, //   INVALID \x8b
  State::INVALID, //   INVALID \x8c
  State::INVALID, //   INVALID \x8d
  State::INVALID, //   INVALID \x8e
  State::INVALID, //   INVALID \x8f
  State::INVALID, //   INVALID \x90
  State::INVALID, //   INVALID \x91
  State::INVALID, //   INVALID \x92
  State::INVALID, //   INVALID \x93
  State::INVALID, //   INVALID \x94
  State::INVALID, //   INVALID \x95
  State::INVALID, //   INVALID \x96
  State::INVALID, //   INVALID \x97
  State::INVALID, //   INVALID \x98
  State::INVALID, //   INVALID \x99
  State::INVALID, //   INVALID \x9a
  State::INVALID, //   INVALID \x9b
  State::INVALID, //   INVALID \x9c
  State::INVALID, //   INVALID \x9d
  State::INVALID, //   INVALID \x9e
  State::INVALID, //   INVALID \x9f
  State::INVALID, //   INVALID \xa0
  State::INVALID, //   INVALID \xa1
  State::INVALID, //   INVALID \xa2
  State::INVALID, //   INVALID \xa3
  State::INVALID, //   INVALID \xa4
  State::INVALID, //   INVALID \xa5
  State::INVALID, //   INVALID \xa6
  State::INVALID, //   INVALID \xa7
  State::INVALID, //   INVALID \xa8
  State::INVALID, //   INVALID \xa9
  State::INVALID, //   INVALID \xaa
  State::INVALID, //   INVALID \xab
  State::INVALID, //   INVALID \xac
  State::INVALID, //   INVALID \xad
  State::INVALID, //   INVALID \xae
  State::INVALID, //   INVALID \xaf
  State::INVALID, //   INVALID \xb0
  State::INVALID, //   INVALID \xb1
  State::INVALID, //   INVALID \xb2
  State::INVALID, //   INVALID \xb3
  State::INVALID, //   INVALID \xb4
  State::INVALID, //   INVALID \xb5
  State::INVALID, //   INVALID \xb6
  State::INVALID, //   INVALID \xb7
  State::INVALID, //   INVALID \xb8
  State::INVALID, //   INVALID \xb9
  State::INVALID, //   INVALID \xba
  State::INVALID, //   INVALID \xbb
  State::INVALID, //   INVALID \xbc
  State::INVALID, //   INVALID \xbd
  State::INVALID, //   INVALID \xbe
  State::INVALID, //   INVALID \xbf
  State::INVALID, //   INVALID \xc0
  State::INVALID, //   INVALID \xc1
  State::INVALID, //   INVALID \xc2
  State::INVALID, //   INVALID \xc3
  State::INVALID, //   INVALID \xc4
  State::INVALID, //   INVALID \xc5
  State::INVALID, //   INVALID \xc6
  State::INVALID, //   INVALID \xc7
  State::INVALID, //   INVALID \xc8
  State::INVALID, //   INVALID \xc9
  State::INVALID, //   INVALID \xca
  State::INVALID, //   INVALID \xcb
  State::INVALID, //   INVALID \xcc
  State::INVALID, //   INVALID \xcd
  State::INVALID, //   INVALID \xce
  State::INVALID, //   INVALID \xcf
  State::INVALID, //   INVALID \xd0
  State::INVALID, //   INVALID \xd1
  State::INVALID, //   INVALID \xd2
  State::INVALID, //   INVALID \xd3
  State::INVALID, //   INVALID \xd4
  State::INVALID, //   INVALID \xd5
  State::INVALID, //   INVALID \xd6
  State::INVALID, //   INVALID \xd7
  State::INVALID, //   INVALID \xd8
  State::INVALID, //   INVALID \xd9
  State::INVALID, //   INVALID \xda
  State::INVALID, //   INVALID \xdb
  State::INVALID, //   INVALID \xdc
  State::INVALID, //   INVALID \xdd
  State::INVALID, //   INVALID \xde
  State::INVALID, //   INVALID \xdf
  State::INVALID, //   INVALID \xe0
  State::INVALID, //   INVALID \xe1
  State::INVALID, //   INVALID \xe2
  State::INVALID, //   INVALID \xe3
  State::INVALID, //   INVALID \xe4
  State::INVALID, //   INVALID \xe5
  State::INVALID, //   INVALID \xe6
  State::INVALID, //   INVALID \xe7
  State::INVALID, //   INVALID \xe8
  State::INVALID, //   INVALID \xe9
  State::INVALID, //   INVALID \xea
  State::INVALID, //   INVALID \xeb
  State::INVALID, //   INVALID \xec
  State::INVALID, //   INVALID \xed
  State::INVALID, //   INVALID \xee
  State::INVALID, //   INVALID \xef
  State::INVALID, //   INVALID \xf0
  State::INVALID, //   INVALID \xf1
  State::INVALID, //   INVALID \xf2
  State::INVALID, //   INVALID \xf3
  State::INVALID, //   INVALID \xf4
  State::INVALID, //   INVALID \xf5
  State::INVALID, //   INVALID \xf6
  State::INVALID, //   INVALID \xf7
  State::INVALID, //   INVALID \xf8
  State::INVALID, //   INVALID \xf9
  State::INVALID, //   INVALID \xfa
  State::INVALID, //   INVALID \xfb
  State::INVALID, //   INVALID \xfc
  State::INVALID, //   INVALID \xfd
  State::INVALID, //   INVALID \xfe
  State::INVALID, //   INVALID \xff
];
